export enum Nationality {
    Afghani = "Afghani",
    Albanian = "Albanian",
    Algerian = "Algerian",
    Andorran = "Andorran",
    Angolan = "Angolan",
    Argentine = "Argentine",
    Armenian = "Armenian",
    Australian = "Australian",
    Austrian = "Austrian",
    Azerbaijani = "Azerbaijani",
    Bahamian = "Bahamian",
    Bahraini = "Bahraini",
    Bangladeshi = "Bangladeshi",
    Barbadian = "Barbadian",
    Belarusian = "Belarusian",
    Belgian = "Belgian",
    Belizean = "Belizean",
    Beninese = "Beninese",
    Bhutanese = "Bhutanese",
    Bolivian = "Bolivian",
    Bosnian = "Bosnian",
    Brazilian = "Brazilian",
    British = "British",
    Bulgarian = "Bulgarian",
    Canadian = "Canadian",
    Chilean = "Chilean",
    Chinese = "Chinese",
    Colombian = "Colombian",
    Congolese = "Congolese",
    Croatian = "Croatian",
    Cuban = "Cuban",
    Cypriot = "Cypriot",
    Czech = "Czech",
    Danish = "Danish",
    Dominican = "Dominican",
    Ecuadorian = "Ecuadorian",
    Egyptian = "Egyptian",
    ElSalvadoran = "El Salvadoran",
    Estonian = "Estonian",
    Ethiopian = "Ethiopian",
    Filipino = "Filipino",
    Finnish = "Finnish",
    French = "French",
    German = "German",
    Greek = "Greek",
    Guatemalan = "Guatemalan",
    Haitian = "Haitian",
    Honduran = "Honduran",
    Hungarian = "Hungarian",
    Icelandic = "Icelandic",
    Indian = "Indian",
    Indonesian = "Indonesian",
    Iranian = "Iranian",
    Iraqi = "Iraqi",
    Irish = "Irish",
    Israeli = "Israeli",
    Italian = "Italian",
    Jamaican = "Jamaican",
    Japanese = "Japanese",
    Jordanian = "Jordanian",
    Kazakh = "Kazakh",
    Kenyan = "Kenyan",
    Korean = "Korean",
    Kuwaiti = "Kuwaiti",
    Latvian = "Latvian",
    Lebanese = "Lebanese",
    Lithuanian = "Lithuanian",
    Luxembourgish = "Luxembourgish",
    Macedonian = "Macedonian",
    Malagasy = "Malagasy",
    Malaysian = "Malaysian",
    Maltese = "Maltese",
    Mexican = "Mexican",
    Moldovan = "Moldovan",
    Mongolian = "Mongolian",
    Moroccan = "Moroccan",
    Nepali = "Nepali",
    Dutch = "Dutch",
    NewZealander = "New Zealander",
    Nicaraguan = "Nicaraguan",
    Nigerian = "Nigerian",
    Norwegian = "Norwegian",
    Omani = "Omani",
    Pakistani = "Pakistani",
    Palestinian = "Palestinian",
    Panamanian = "Panamanian",
    Paraguayan = "Paraguayan",
    Peruvian = "Peruvian",
    Polish = "Polish",
    Portuguese = "Portuguese",
    Qatari = "Qatari",
    Romanian = "Romanian",
    Russian = "Russian",
    Rwandan = "Rwandan",
    Saudi = "Saudi",
    Singaporean = "Singaporean",
    Slovak = "Slovak",
    Slovenian = "Slovenian",
    SouthAfrican = "South African",
    Spanish = "Spanish",
    SriLankan = "Sri Lankan",
    Sudanese = "Sudanese",
    Swedish = "Swedish",
    Swiss = "Swiss",
    Syrian = "Syrian",
    Taiwanese = "Taiwanese",
    Tanzanian = "Tanzanian",
    Thai = "Thai",
    Tunisian = "Tunisian",
    Turkish = "Turkish",
    Ugandan = "Ugandan",
    Ukrainian = "Ukrainian",
    Emirati = "Emirati",
    BritishVirginIslander = "British Virgin Islander",
    American = "American",
    Venezuelan = "Venezuelan",
    Vietnamese = "Vietnamese",
    Welsh = "Welsh",
    Zambian = "Zambian",
    Zimbabwean = "Zimbabwean"
}
export const getNationalityInArabic = (nationality: Nationality): string => {
    const translations: { [key in Nationality]: string } = {
        [Nationality.Afghani]: "أفغاني",
        [Nationality.Albanian]: "ألباني",
        [Nationality.Algerian]: "جزائري",
        [Nationality.Andorran]: "أندوري",
        [Nationality.Angolan]: "أنغولي",
        [Nationality.Argentine]: "أرجنتيني",
        [Nationality.Armenian]: "أرميني",
        [Nationality.Australian]: "أسترالي",
        [Nationality.Austrian]: "نمساوي",
        [Nationality.Azerbaijani]: "أذري",
        [Nationality.Bahamian]: "باهامي",
        [Nationality.Bahraini]: "بحريني",
        [Nationality.Bangladeshi]: "بنغالي",
        [Nationality.Barbadian]: "باربادوسي",
        [Nationality.Belarusian]: "بيلاروسي",
        [Nationality.Belgian]: "بلجيكي",
        [Nationality.Belizean]: "بليزاني",
        [Nationality.Beninese]: "بنيني",
        [Nationality.Bhutanese]: "بوتاني",
        [Nationality.Bolivian]: "بوليفي",
        [Nationality.Bosnian]: "بوسني",
        [Nationality.Brazilian]: "برازيلي",
        [Nationality.British]: "بريطاني",
        [Nationality.Bulgarian]: "بلغاري",
        [Nationality.Canadian]: "كندي",
        [Nationality.Chilean]: "شيلي",
        [Nationality.Chinese]: "صيني",
        [Nationality.Colombian]: "كولومبي",
        [Nationality.Congolese]: "كونغولي",
        [Nationality.Croatian]: "كرواتي",
        [Nationality.Cuban]: "كوبي",
        [Nationality.Cypriot]: "قبرصي",
        [Nationality.Czech]: "تشيكي",
        [Nationality.Danish]: "دنماركي",
        [Nationality.Dominican]: "دومينيكاني",
        [Nationality.Ecuadorian]: "إكوادوري",
        [Nationality.Egyptian]: "مصري",
        [Nationality.ElSalvadoran]: "سلفادوري",
        [Nationality.Estonian]: "إستوني",
        [Nationality.Ethiopian]: "إثيوبي",
        [Nationality.Filipino]: "فلبيني",
        [Nationality.Finnish]: "فنلندي",
        [Nationality.French]: "فرنسي",
        [Nationality.German]: "ألماني",
        [Nationality.Greek]: "يوناني",
        [Nationality.Guatemalan]: "غواتيمالي",
        [Nationality.Haitian]: "هايتي",
        [Nationality.Honduran]: "هندوراسي",
        [Nationality.Hungarian]: "مجري",
        [Nationality.Icelandic]: "أيسلندي",
        [Nationality.Indian]: "هندي",
        [Nationality.Indonesian]: "إندونيسي",
        [Nationality.Iranian]: "إيراني",
        [Nationality.Iraqi]: "عراقي",
        [Nationality.Irish]: "إيرلندي",
        [Nationality.Israeli]: "إسرائيلي",
        [Nationality.Italian]: "إيطالي",
        [Nationality.Jamaican]: "جامايكي",
        [Nationality.Japanese]: "ياباني",
        [Nationality.Jordanian]: "أردني",
        [Nationality.Kazakh]: "كازاخي",
        [Nationality.Kenyan]: "كيني",
        [Nationality.Korean]: "كوري",
        [Nationality.Kuwaiti]: "كويتي",
        [Nationality.Latvian]: "لاتفي",
        [Nationality.Lebanese]: "لبناني",
        [Nationality.Lithuanian]: "ليتواني",
        [Nationality.Luxembourgish]: "لوكسمبرغي",
        [Nationality.Macedonian]: "مقدوني",
        [Nationality.Malagasy]: "ملغاشي",
        [Nationality.Malaysian]: "ماليزي",
        [Nationality.Maltese]: "مالطي",
        [Nationality.Mexican]: "مكسيكي",
        [Nationality.Moldovan]: "مولدوفي",
        [Nationality.Mongolian]: "منغولي",
        [Nationality.Moroccan]: "مغربي",
        [Nationality.Nepali]: "نيبالي",
        [Nationality.Dutch]: "هولندي",
        [Nationality.NewZealander]: "نيوزيلندي",
        [Nationality.Nicaraguan]: "نيكاراغوي",
        [Nationality.Nigerian]: "نيجيري",
        [Nationality.Norwegian]: "نرويجي",
        [Nationality.Omani]: "عماني",
        [Nationality.Pakistani]: "باكستاني",
        [Nationality.Palestinian]: "فلسطيني",
        [Nationality.Panamanian]: "بنمي",
        [Nationality.Paraguayan]: "باراغواياني",
        [Nationality.Peruvian]: "بيروفي",
        [Nationality.Polish]: "بولندي",
        [Nationality.Portuguese]: "برتغالي",
        [Nationality.Qatari]: "قطري",
        [Nationality.Romanian]: "روماني",
        [Nationality.Russian]: "روسي",
        [Nationality.Rwandan]: "رواندي",
        [Nationality.Saudi]: "سعودي",
        [Nationality.Singaporean]: "سنغافوري",
        [Nationality.Slovak]: "سلوفاكي",
        [Nationality.Slovenian]: "سلوفيني",
        [Nationality.SouthAfrican]: "جنوب أفريقي",
        [Nationality.Spanish]: "إسباني",
        [Nationality.SriLankan]: "سريلانكي",
        [Nationality.Sudanese]: "سوداني",
        [Nationality.Swedish]: "سويدي",
        [Nationality.Swiss]: "سويسري",
        [Nationality.Syrian]: "سوري",
        [Nationality.Taiwanese]: "تايواني",
        [Nationality.Tanzanian]: "تنزاني",
        [Nationality.Thai]: "تايلاندي",
        [Nationality.Tunisian]: "تونسي",
        [Nationality.Turkish]: "تركي",
        [Nationality.Ugandan]: "أوغندي",
        [Nationality.Ukrainian]: "أوكراني",
        [Nationality.Emirati]: "إماراتي",
        [Nationality.BritishVirginIslander]: "بريطاني من جزر العذراء",
        [Nationality.American]: "أمريكي",
        [Nationality.Venezuelan]: "فنزويلي",
        [Nationality.Vietnamese]: "فيتنامي",
        [Nationality.Welsh]: "ويلزي",
        [Nationality.Zambian]: "زامبي",
        [Nationality.Zimbabwean]: "زيمبابوي"
    };
    return translations[nationality] || "Unknown Nationality";
};
